### ISSUE TITLE
windhawkバグってファイルピッカー変えられないんですけど！！！！！１１１！！れれれれれ！！！１１１！！！

### ISSUE THREAD

**Issue by minotto165** [pap-git/EdibleDLP#11]
### _SHINE_
![C687F064-AA3C-4A87-8922-79ABA60D67EA](https://github.com/user-attachments/assets/8bdfdfea-08c7-4623-be6a-5460d02df9df)

**Comment by pap-git** [comment]
# 知るか
Windhawkの問題なので対応できません。
